# build stage 
FROM node:20-alpine AS build-stage 
WORKDIR /app 
COPY package*.json ./ 
RUN npm install 
COPY . . 
RUN npm run build 
# production stage 
FROM nginx:stable-alpine AS production-stage 
COPY --from=build-stage /app/dist /usr/share/nginx/html 
COPY ./nginx-vue-app.conf /etc/nginx/conf.d/default.conf 

FROM alpine/java:21 
#RUN #addgroup -S spring && adduser -S spring -G spring 
EXPOSE 8080 
ENV JAVA_PROFILE=prod 
ARG DEPENDENCY=target/dependency 
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib 
COPY ${DEPENDENCY}/META-INF /app/META-INF 
COPY ${DEPENDENCY}/BOOT-INF/classes /app 
ENTRYPOINT ["java" ,   "-Dspring.profiles.active=${JAVA_PROFILE}",\ 
"-cp","app:app/lib/*","se331.lab.Application"]